### PR TITLE
pyramid_tm explicit manager value on the settings.

### PR DESCRIPTION
**Pull request by chrismorales**

### CODE REVIEW

**Comment by stevepiercy** [comment]
@chrismorales thank you! Please see my comment https://github.com/Pylons/pyramid/issues/3052#issuecomment-303498276 so that the docs stay aligned with this PR.

**Review by digitalresistor — APPROVED** [review]

**Comment by stevepiercy** [comment]
Merge awaits completion of https://github.com/Pylons/pyramid/pull/3059

**Review by stevepiercy — DISMISSED** [review]
See comment on https://github.com/Pylons/pyramid/pull/3059#pullrequestreview-39888025

**Comment by stevepiercy** [comment]
See Pylons/pyramid#3081

**Pull request merged**
