### PR TITLE
get rid of the transaction.commit() in the models.appmaker function

### PR DESCRIPTION
**Pull request by stevepiercy**
- see #22

### CODE REVIEW

**Comment by mmerickel** [comment]
https://github.com/Pylons/pyramid_zodbconn/pull/10 should fix the remaining issues with the explicit manager so we can merge this after that gets released.

**Comment by stevepiercy** [comment]
Hold off on backport to 1.9, until I get the chance to handle #21. Two issues, one backport.

**Comment by mmerickel** [comment]
This should get cherry-picked into the 1.9-branch and latest branches.

**Comment by stevepiercy** [comment]
Yeah, and I need to check for updates to Pyramid docs, too.

**Comment by stevepiercy** [comment]
Backport done in #24 and #25.

I am stuck on the context manager issue in #21.

**Pull request merged**
